### ISSUE TITLE
No Html.EditroFor/DisplayFor overloads

### ISSUE THREAD

**Issue by SpearOne** [johnnyreilly/jQuery.Validation.Unobtrusive.Native#16]
Hi

I've noticed that there are no overloaded functions for Html.EditroFor/DisplayFor, this means that the validation attributes that are generated are using the old data-val attributes instead of the new data-rule attributes. Is there anyway we could add support for this in another release?

**Comment by johnnyreilly** [comment]
Hi,

`DisplayFor` doesn't really have any purpose from a validation perspective.  `EditorFor` can be controlled using templates and so I don't plan to add support myself.
