### ISSUE TITLE
Support for EnumDropDownListFor

### ISSUE THREAD

**Issue by bubb-rubb** [johnnyreilly/jQuery.Validation.Unobtrusive.Native#23]
any plans to include EnumDropDownListFor?

**Comment by johnnyreilly** [comment]
Not at present... But PRs are welcome!

**Comment by johnnyreilly** [comment]
Working on this now...

**Comment by johnnyreilly** [comment]
Resolved by https://github.com/johnnyreilly/jQuery.Validation.Unobtrusive.Native/commit/d298bf303b5f196d3a3ba8b60b936638d6d175d9

Documentation website not yet updated so will leave this open for now as a reminder.

**Comment by bubb-rubb** [comment]
Great! Thanks for your effort!
