### ISSUE TITLE
ValidationMessage and ValidationSummary

### ISSUE THREAD

**Issue by maxtoroq** [johnnyreilly/jQuery.Validation.Unobtrusive.Native#28]
Your project does not support ValidationMessage and ValidationSummary, I think you should document that. While nothing stops you from using ValidationMessage and ValidationSummary, you cannot share the same element to display server and client messages, hide the server message when validating, show messages in the summary instead by each individual control, etc. These features are exclusive to the unobtrusive library.

**Comment by johnnyreilly** [comment]
Hi, I'm not supporting this project directly anymore. If you'd like to send a docs PR I'll take a look though
